id: P19CB9B68
initial_creation_type: ocr
source_metadata:
  volumes:
    907ff2d3563141248cdadf12e135da15:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: འཕགས་པ་རྟ་མགྲིན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1044
      volume_number: 38
