id: DC037F761
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:36:09+00:00'
last_modified: '2022-05-26T12:29:30.197535+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    17b1:
      image_group_id: I1PD95883
      title: འཕགས་པ་རྟ་མགྲིན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1044
      order: 38
      base_file: 17b1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
